### ISSUE TITLE
Page title says Express

### ISSUE THREAD

**Issue by jeffskelton3** [tcb1978/hypemachine_player#16]
set that to HypeMachine player or something

**Comment by tcb1978** [comment]
I added it the old fashioned way replacing the '<%= title %>' within the head tags. Should I have done something else using that snippet?

**Comment by jeffskelton3** [comment]
Naw thats fine. The <%= %> stuff are variables being sent from the node
server and we aren’t covering that stuff yet

## 

Jeff Skelton
jeff@jeffskelton.net

On August 24, 2016 at 2:35:46 PM, tcb1978 (notifications@github.com) wrote:

Closed #16 https://github.com/tcb1978/hypemachine_player/issues/16.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/tcb1978/hypemachine_player/issues/16#event-766642233,
or mute the thread
